var albums = [
  { type: "album",
    albumTitle: "Album 1" ,
    albumCover: "images/album1/large/photo1_1.jpeg",
    albumRel: "album-1",
    photos:  [
      { photoName: "photo1" ,
        photoRel: "photo_1",
        photoFull: "images/album1/large/photo1_1.jpeg",
      },
      { photoName: "photo2" ,
        photoRel: "photo_2",
        photoFull: "images/album1/large/photo1_2.jpeg",
      },
      { photoName: "photo3" ,
        photoRel: "photo_3",
        photoFull: "images/album1/large/photo1_3.jpeg",
      },
      { photoName: "photo4" ,
        photoRel: "photo_4",
        photoFull: "images/album1/large/photo1_4.jpeg",
      },
      { photoName: "photo5" ,
        photoRel: "photo_5",
        photoFull: "images/album1/large/photo1_5.jpeg",
      },
      { photoName: "photo6" ,
        photoRel: "photo_6",
        photoFull: "images/album1/large/photo1_6.jpeg",
      },
    ],
  },
  { type: "album",
    albumTitle: "Album 2" ,
    albumCover: "images/album2/large/photo2_1.jpeg",
    albumRel: "album-2",
    photos: [
      { photoName: "photo1" ,
        photoRel: "photo_1",
        photoFull: "images/album2/large/photo2_1.jpeg",
      },
      { photoName: "photo2" ,
        photoRel: "photo_2",
        photoFull: "images/album2/large/photo2_2.jpeg",
      },
      { photoName: "photo3" ,
        photoRel: "photo_3",
        photoFull: "images/album2/large/photo2_3.jpeg",
      },
      { photoName: "photo4" ,
        photoRel: "photo_4",
        photoFull: "images/album2/large/photo2_4.jpeg",
      },
      { photoName: "photo5" ,
        photoRel: "photo_5",
        photoFull: "images/album2/large/photo2_5.jpeg",
      },
      { photoName: "photo6" ,
        photoRel: "photo_6",
        photoFull: "images/album2/large/photo2_6.jpeg",
      },
    ],
  },
  { type: "album",
    albumTitle: "Album 3" ,
    albumCover: "images/album3/large/photo3_1.jpeg",
    albumRel: "album-3",
    photos: [
      { photoName: "photo1" ,
        photoRel: "photo_1",
        photoFull: "images/album3/large/photo3_1.jpeg",
      },
      { photoName: "photo2" ,
        photoRel: "photo_2",
        photoFull: "images/album3/large/photo3_2.jpeg",
      },
      { photoName: "photo3" ,
        photoRel: "photo_3",
        photoFull: "images/album3/large/photo3_3.jpeg",
      },
      { photoName: "photo4" ,
        photoRel: "photo_4",
        photoFull: "images/album3/large/photo3_4.jpeg",
      },
      { photoName: "photo5" ,
        photoRel: "photo_5",
        photoFull: "images/album3/large/photo3_5.jpeg",
      },
      { photoName: "photo6" ,
        photoRel: "photo_6",
        photoFull: "images/album3/large/photo3_6.jpeg",
      },
    ],
  },
  { type: "album",
    albumTitle: "Album 4" ,
    albumCover: "images/album4/large/photo4_1.jpeg",
    albumRel: "album-4",
    photos: [
      { photoName: "photo1" ,
        photoRel: "photo_1",
        photoFull: "images/album4/large/photo4_1.jpeg",
      },
      { photoName: "photo2" ,
        photoRel: "photo_2",
        photoFull: "images/album4/large/photo4_2.jpeg",
      },
      { photoName: "photo3" ,
        photoRel: "photo_3",
        photoFull: "images/album4/large/photo4_3.jpeg",
      },
      { photoName: "photo4" ,
        photoRel: "photo_4",
        photoFull: "images/album4/large/photo4_4.jpeg",
      },
      { photoName: "photo5" ,
        photoRel: "photo_5",
        photoFull: "images/album4/large/photo4_5.jpeg",
      },
      { photoName: "photo6" ,
        photoRel: "photo_6",
        photoFull: "images/album4/large/photo4_6.jpeg",
      },
    ],
  },
  { type: "album",
    albumTitle: "Album 5" ,
    albumCover: "images/album5/large/photo5_1.jpeg",
    albumRel: "album-5",
    photos: [
      { photoName: "photo1" ,
        photoRel: "photo_1",
        photoFull: "images/album5/large/photo5_1.jpeg",
      },
      { photoName: "photo2" ,
        photoRel: "photo_2",
        photoFull: "images/album5/large/photo5_2.jpeg",
      },
      { photoName: "photo3" ,
        photoRel: "photo_3",
        photoFull: "images/album5/large/photo5_3.jpeg",
      },
      { photoName: "photo4" ,
        photoRel: "photo_4",
        photoFull: "images/album5/large/photo5_4.jpeg",
      },
      { photoName: "photo5" ,
        photoRel: "photo_5",
        photoFull: "images/album5/large/photo5_5.jpeg",
      },
      { photoName: "photo6" ,
        photoRel: "photo_6",
        photoFull: "images/album5/large/photo5_6.jpeg",
      },
    ],
  },
  { type: "album",
    albumTitle: "Album 6" ,
    albumCover: "images/album6/large/photo6_1.jpeg",
    albumRel: "album-6",
    photos: [
      { photoName: "photo1" ,
        photoRel: "photo_1",
        photoFull: "images/album6/large/photo6_1.jpeg",
      },
      { photoName: "photo2" ,
        photoRel: "photo_2",
        photoFull: "images/album6/large/photo6_2.jpeg",
      },
      { photoName: "photo3" ,
        photoRel: "photo_3",
        photoFull: "images/album6/large/photo6_3.jpeg",
      },
      { photoName: "photo4" ,
        photoRel: "photo_4",
        photoFull: "images/album6/large/photo6_4.jpg",
      },
      { photoName: "photo5" ,
        photoRel: "photo_5",
        photoFull: "images/album6/large/photo6_5.jpeg",
      },
      { photoName: "photo6" ,
        photoRel: "photo_6",
        photoFull: "images/album6/large/photo6_6.jpeg",
      },
    ],
  },
];
